config/routes.rb
Rails.application.routes.draw do
  get 'crypto_market/buy'
  post 'crypto_market/confirm'
  get 'crypto_market/confirm'
  get 'crypto_market/refresh'
  get 'crypto_market/update_quantity'
  get 'portfolio/view'
  get 'portfolio/reset'
  post'portfolio/add_asset'

  resources :assets
  resources :bought_assets

  root 'portfolio#view'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
	def new(asset_id, asset_name, asset_value)
		@asset_id = asset_id
		@asset_name = asset_name
		@asset_value = asset_value
	end
end

app/models/assets_available.rb
class AssetsAvailable < ApplicationRecord
	def new(quantity)
		@quantity = quantity
	end
end

app/models/bought_asset.rb
class BoughtAsset < ApplicationRecord
	def new(asset_id, asset_name, asset_value, quantity)
		@asset_id = asset_id
		@asset_name = asset_name
		@asset_value = asset_value
		@quantity = quantity
	end
end

app/models/last_updated.rb
class LastUpdated < ApplicationRecord
	def new(last_updated)
		@last_updated = last_updated
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
	def new
	end
end

app/controllers/crypto_market_controller.rb
require 'net/http'
require 'openssl'
require 'date'
require 'json'
require 'assets_controller'
require 'asset'

# Helper method to obtain http requests, given a URI.
def request_uri(uri = "", parameters = {})
  	uri = URI.join(uri)
	uri.query = URI.encode_www_form(parameters)
	request = Net::HTTP::Get.new(uri)
	http = Net::HTTP.new(uri.host, uri.port)
	http.use_ssl = true
	response = http.request(request)
	JSON.parse(response.body, symbolize_names: true)
end

# Class responsible for fetching and showing all available assets and their values.
class CryptoMarketController < ApplicationController
  def buy 	# Shows the avaiable assets that can be bought.
  	find_values
	@assets = Asset.all
	@last_updated = LastUpdated.first
	@assets_available = AssetsAvailable.first.quantity
  end
  def update_quantity 	# Updates the number of assets shown in the list.
  	quantity = params[:asset_quantity]["quantity"]
  	if (AssetsAvailable.first.nil?)
		@assets_available = AssetsAvailable.new(quantity: quantity)
	else
		@assets_available = AssetsAvailable.first
		@assets_available.quantity = quantity
	end
	@assets_available.save
	redirect_to action: "refresh"
  end
  def refresh 	# Clears the assets stored in the model, and refills it with updated values. Also uptates the value of previously bought assets.
  	Asset.delete_all
  	find_values
  	assets = Asset.all
  	for asset in assets
  		bought_asset = BoughtAsset.find_by asset_id:asset.asset_id
  		if not bought_asset.nil?
  			bought_asset.asset_value = asset.asset_value
  			bought_asset.save
  		end
  	end
  	redirect_to action: "buy"
  end
  def find_values	# Checks if the assets model is empty. If it is, fills it with the assets from the API.
  	if Asset.first.nil? 
  		if (AssetsAvailable.first.nil?)
  			@assets_available = AssetsAvailable.new(quantity: 10)
  			@assets_available.save
  		end
  		@assets_available = AssetsAvailable.first.quantity
	  	coins = request_uri("https://min-api.cryptocompare.com/data/top/totalvol", {'limit': @assets_available, 'tsym': 'USD'})[:Data]
	  	best_coins = {}
		for coin in coins
			best_coins[coin[:CoinInfo][:Name]] = coin[:CoinInfo][:FullName] 
		end
	  	puts best_coins
		rates = request_uri("https://min-api.cryptocompare.com/data/pricemulti", {'fsyms': best_coins.keys.join(','), 'tsyms': 'USD'})
		for id, value in rates
			asset = Asset.new(asset_id: id, asset_name: best_coins[id.to_s], asset_value: value[:USD])
			asset.save
		end
		if (LastUpdated.first.nil?)
			@last_updated = LastUpdated.new(date: DateTime.now.strftime("%b %d, %Y, %H:%I:%M"))
		else
			@last_updated = LastUpdated.first
			@last_updated.date = DateTime.now.strftime("%d %b %Y, %H:%M:%S")
		end
		@last_updated.save
	end
  end
  def confirm 	# Confirms the purchase of a specific asset.
  	@assets = Asset.all
  	@buy_id = params[:data]
  end
end

app/controllers/portfolio_controller.rb
# Controls the actions related to the asset portfolio.
class PortfolioController < ApplicationController
  def view	# View the currently bought assets.
  	@bought_assets = BoughtAsset.all
  end
  def reset  # Clear the portfolio.
  	BoughtAsset.delete_all
  	redirect_to action: "view"
  end
  def add_asset # Adds a new asset to the portfolio, after it is bought.  
  	id = params[:asset_quantity]["id"]
  	quantity = params[:asset_quantity]["quantity"]
  	if quantity.to_i > 0 
		@asset = Asset.find_by asset_id:id
		@bought_asset = BoughtAsset.find_by asset_id:id
		if @bought_asset.nil?
			@bought_asset = BoughtAsset.new(asset_id: id, asset_name: @asset.asset_name, asset_value: @asset.asset_value, quantity: quantity)
		else
			@bought_asset.quantity = @bought_asset.quantity.to_f + quantity.to_f
		end
		@bought_asset.save
	end
  	redirect_to action: "view"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/crypto_market_helper.rb
module CryptoMarketHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/crypto_market/buy.html.erb
<style>
th, td {
    padding: 5px;
}
.button {
    padding: 10px 15px;
}
</style>
<center><h1>Crypto Market</h1>
<%= form_with scope: :asset_quantity, url: crypto_market_update_quantity_path, method: :get,local: true do |form| %>Showing <%= form.number_field 'quantity', {value: @assets_available, min: 10, max: 70, step: 10} %> of the best Cryptocurrencies, volume-wise.&nbsp;&nbsp;&nbsp;
<%= form.submit "Update Quantity", class: :button %>
<% end %><br>

<table id="t01">
  <tr>
    <th>Asset Name</th>
    <th>Asset ID</th>
    <th>Asset Value</th>
    <th>Buy</th>
  </tr>
  <% @assets.each do |asset| %>
    <tr>
    	<td><b><%= asset.asset_name %></b></td>
    	<td><%= asset.asset_id %></td>
    	<td>US$ <%= asset.asset_value.round(5) %></td>
    	<td><%= button_to 'Buy', {action: "confirm", data: asset.asset_id}, {class: 'button'} %></td>
    </tr>
  <% end %>
</table>
<p>
Last updated: <%= @last_updated.date %>. Source: <a href="https://www.cryptocompare.com/">CryptoCompare</a>
<%= form_with url: crypto_market_refresh_path, method: :get,local: true do |form| %>
    <%= form.submit "Update Values", class: :button %>
<% end %><br>
<%= form_with url: portfolio_view_path, method: :get,local: true do |form| %>
    <%= form.submit "Back", class: :back_button %>
<% end %>
</p>
</center>

app/views/crypto_market/confirm.html.erb
<style>
th, td {
    padding: 5px;
}	
</style>
<center><h1>Confirm Purchase</h1>
<h2>Do you really want to buy this asset?</h2>
<table id="t01">
  <tr>
    <th>Asset Name</th>
    <th>Asset ID</th>
    <th>Asset Value</th>
    <th>Quantity</th>
    <th>Buy</th>
  </tr>
  <% @assets.each do |asset| %>
  	<% if asset.asset_id == @buy_id %>
    	<tr>
    		<td><b><%= asset.asset_name %></b></td>
    		<td><%= asset.asset_id %></td>
    		<td>US$ <%= asset.asset_value %></td>
    		<%=form_with scope: :asset_quantity, url: portfolio_add_asset_path do |form|%>
    			<%=form.hidden_field 'id', value: asset.asset_id %>
    			<td><%= form.number_field 'quantity', {value: 0, min: 0, step: 1} %></td>
    			<td><%= form.submit 'Confirm Operation', {class: 'button'} %></td>
    		<%end%>
    	</tr>
    <% end %>
  <% end %>
</table><br>
<%= form_with url: crypto_market_buy_path, method: :get,local: true do |form| %>
    <%= form.submit "Back", class: :back_button %>
<% end %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoPortfolioRodrigo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/portfolio/view.html.erb
<style>
form {
    display: inline-block;
}
</style>

<center><h1>Cryptocurrency Portfolio</h1>
	<p>Developed by Rodrigo Teixeira. <a href="https://github.com/teixeira0/crypto-portfolio-rodrigo">Github</a></p>
<table id="t01">
  <tr>
    <th>Asset Name</th>
    <th>Asset ID</th>
    <th>Asset Value</th>
    <th>Quantity</th>
    <th>Total Value</th>
  </tr>
  <% if not @bought_assets.nil?%>
	  <% @bought_assets.each do |asset| %>
	    <tr>
	    	<td><b><%= asset.asset_name %></b></td>
	    	<td><%= asset.asset_id %></td>
	    	<td>US$ <%= asset.asset_value.round(5) %></td>
	    	<td><%= asset.quantity.to_i %></td>
	    	<td>US$ <%= (asset.asset_value * asset.quantity).round(5) %></td>
	    </tr>
	  <% end %>
  <% end %>
</table>
<p>
<%= form_with url: portfolio_reset_path, method: :get,local: true do |form| %>
    <%= form.submit "Clear Portfolio", class: :back_button %>
<% end %>&nbsp;
<%= form_with url: crypto_market_buy_path, method: :get,local: true do |form| %>
    <%= form.submit "Buy Assets", class: :button %>
<% end %>
</p>
</center>